/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FirebaseTestJavaSwing;

import java.util.ArrayList;
import javax.swing.*;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle;
import javax.swing.ListModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.JList;
import javax.swing.JOptionPane;

/**
 *
 * @author shahi
 */
public class HomeFrame extends javax.swing.JFrame {

    DB_Functions dbFunctions;

    /**
     * Creates new form HomeFrame
     */
    public HomeFrame() {
        initComponents();
        initComponents();
        dbFunctions = new DB_Functions();

        //ArrayList<Ambulance> ambulanceList = dbFunctions.getAmbulanceList();
        ///ambulanceListView.setModel(model);
//        jList1.addListSelectionListener(listSelectionListener);
        jScrollPane1.setViewportView(dbFunctions.getAmbulanceList(selectedItemView));

//        selectedItemView.setText(""+jList1.getSelectedIndex());
//        
//        System.out.println("First index: " + jList1.getSelectedIndex());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    // Generated using JFormDesigner Evaluation license - unknown
    private void initComponents() {
        jButton1 = new JButton();
        jScrollPane1 = new JScrollPane();
        jList1 = new JList<>();
        selectedItemView = new JLabel();
        bookingNameEditField = new JTextField();
        jButton2 = new JButton();
        bookingPhoneEditField = new JTextField();
        selectedItemView1 = new JLabel();
        selectedItemView2 = new JLabel();

        //======== this ========
        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        var contentPane = getContentPane();

        //---- jButton1 ----
        jButton1.setText("Logout");
        jButton1.addActionListener(e -> jButton1ActionPerformed(e));

        //======== jScrollPane1 ========
        {

            //---- jList1 ----
            jList1.setModel(new AbstractListModel<String>() {
                String[] values = {
                    "Item 1",
                    "Item 2",
                    "Item 3",
                    "Item 4",
                    "Item 5"
                };
                @Override
                public int getSize() { return values.length; }
                @Override
                public String getElementAt(int i) { return values[i]; }
            });
            jScrollPane1.setViewportView(jList1);
        }

        //---- bookingNameEditField ----
        bookingNameEditField.addActionListener(e -> bookingNameEditFieldActionPerformed(e));

        //---- jButton2 ----
        jButton2.setText("Booking");
        jButton2.addActionListener(e -> jButton2ActionPerformed(e));

        //---- bookingPhoneEditField ----
        bookingPhoneEditField.addActionListener(e -> bookingPhoneEditFieldActionPerformed(e));

        //---- selectedItemView1 ----
        selectedItemView1.setText("Enter your name");

        //---- selectedItemView2 ----
        selectedItemView2.setText("Enter your contact number");

        GroupLayout contentPaneLayout = new GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                    .addGap(0, 589, Short.MAX_VALUE)
                    .addComponent(jButton1))
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addGap(26, 26, 26)
                    .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 297, GroupLayout.PREFERRED_SIZE)
                    .addGroup(contentPaneLayout.createParallelGroup()
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addGap(34, 34, 34)
                            .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                                .addComponent(selectedItemView, GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                .addComponent(bookingNameEditField)
                                .addComponent(bookingPhoneEditField)
                                .addComponent(selectedItemView1, GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE)
                                .addComponent(selectedItemView2, GroupLayout.DEFAULT_SIZE, 292, Short.MAX_VALUE))
                            .addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(GroupLayout.Alignment.TRAILING, contentPaneLayout.createSequentialGroup()
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2)
                            .addGap(121, 121, 121))))
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup()
                .addGroup(contentPaneLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton1)
                    .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(contentPaneLayout.createParallelGroup(GroupLayout.Alignment.LEADING, false)
                        .addGroup(contentPaneLayout.createSequentialGroup()
                            .addComponent(selectedItemView, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(selectedItemView1, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(bookingNameEditField, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(selectedItemView2, GroupLayout.PREFERRED_SIZE, 35, GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(bookingPhoneEditField, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED, GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton2))
                        .addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 325, GroupLayout.PREFERRED_SIZE))
                    .addContainerGap(32, Short.MAX_VALUE))
        );
        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Utilitis.setLogin(false);
        this.dispose();
        new LoginFrame().show();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void bookingNameEditFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingNameEditFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingNameEditFieldActionPerformed

    private void bookingPhoneEditFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingPhoneEditFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookingPhoneEditFieldActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (Common.selectedAmbulanc == null) {
            JOptionPane.showMessageDialog(this, "Please select any ambulance");
        } else {
            String name = bookingNameEditField.getText().toString();
            String phone = bookingPhoneEditField.getText().toString();
            if (phone.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Please enter your phone number");
            } else {
                Common.bookingName = name;
                Common.bookingPhone = phone;
                new PaymentLocationFrame().show();
            }
        }

    }//GEN-LAST:event_jButton2ActionPerformed

//    jList1.addListSelectionListener(listSelectionListener);
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // Generated using JFormDesigner Evaluation license - unknown
    private JButton jButton1;
    private JScrollPane jScrollPane1;
    private JList<String> jList1;
    private JLabel selectedItemView;
    private JTextField bookingNameEditField;
    private JButton jButton2;
    private JTextField bookingPhoneEditField;
    private JLabel selectedItemView1;
    private JLabel selectedItemView2;
    // End of variables declaration//GEN-END:variables
}
